### ISSUE TITLE
Using exoplayer:2.8.3 in demo app cause crash in PlayerFragment

### ISSUE THREAD

**Issue by LenaDev** [Firekast-io/firekast-demo-android#2]
09-12 15:58:39.385 20749-20749/io.firekast.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.firekast.demo, PID: 20749
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class io.firekast.FKPlayerView
    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class io.firekast.FKPlayerView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at io.firekast.demo.PlayerFragment.onCreateView(PlayerFragment.kt:26)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NoSuchMethodError: No virtual method setPlayer(Lcom/google/android/exoplayer2/SimpleExoPlayer;)V in class Lcom/google/android/exoplayer2/ui/SimpleExoPlayerView; or its super classes (declaration of 'com.google.android.exoplayer2.ui.SimpleExoPlayerView' appears in /data/app/io.firekast.demo-tZS1qaJy0xEqFgw8CoxeHQ==/split_lib_dependencies_apk.apk)
        at io.firekast.FKPlayerView.b(Unknown Source:118)
        at io.firekast.FKPlayerView.<init>(Unknown Source:13)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at io.firekast.demo.PlayerFragment.onCreateView(PlayerFragment.kt:26) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by LenaDev** [comment]
Can you please update FKPlayerView, so I'll managed to use this version of exoplayer?

**Comment by francoisrouault** [comment]
Hi :) Would version 2.8.4 (latest at the time of writing) be right for you?

**Comment by LenaDev** [comment]
Hi:) Yes, it would be great

**Comment by francoisrouault** [comment]
Done! Please update your `app.gradle` dependencies block with
```
implementation ('io.firekast:firekast:1.2.0') {
     exclude module: 'support-v7'
     exclude module: 'support-v13'
}
```
I let you close the issue if everything is fine for you. Feel free to contact us (contact@firekast.io) if you have any other questions.

**Comment by LenaDev** [comment]
Thank you very much, it's working now. 
Is there any way to use exoplayer itself instead FKPlayerView, for example if I need custom ui for player?
