### ISSUE TITLE
Intermittent crashes while live streaming

### ISSUE THREAD

**Issue by crjacinro** [Firekast-io/firekast-demo-android#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'io.firekast.FKStream$State io.firekast.FKStream.getState()' on a null object reference
        at io.firekast.FKStreamer.a(Unknown Source:4)
        at io.firekast.FKStreamer.a(Unknown Source:0)
        at io.firekast.FKStreamer$a$1.done(Unknown Source:17)
        at io.firekast.FKStream$1.a(Unknown Source:2)
        at io.firekast.n.onPostExecute(Unknown Source:28)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by francoisrouault** [comment]
Hi, thank you for your feedback! I going to look at it.
Could you tell which version of the SDK you use (cf. `build.gradle` file) ? And on which device(s) did you test and found that crash ? 
Thank you, Regards

**Comment by crjacinro** [comment]
I am using 1.2.4.  I can encounter it in emulators and real devices, (samsung, huawei) seems like its not device specific. 

Also, I am seeing 1.4.0 version but lots of interface changes to be done. Need to update this repository also that supports newer version

**Comment by crjacinro** [comment]
> I am using 1.2.4. I can encounter it in emulators and real devices, (samsung, huawei) seems like its not device specific.
>  
> Also, I am seeing 1.4.0 version but lots of interface changes to be done. Need to update this repository also that supports newer version


opps sorry. repo is being updated.  I missed it

**Comment by francoisrouault** [comment]
Great, this bug has been indeed found and fixed in v1.2.5 so we recommend you update the SDK to this version, at least. This update is just bug fixes so it will not impact your code.
Keep us inform if you have any question! :)
